#!/bin/sh

parallel -i -j100 ssh -oBatchMode=yes -oConnectTimeout=2 {} 'test -z "$(users)" && echo $(cut -d" " -f1-3 /proc/loadavg) {}' -- \
  albatrossi broileri dodo drontti emu fasaani flamingo iibis kakadu kalkkuna karakara kasuaari kiuru kiwi kolibri \
  kondori kookaburra koskelo kuukkeli lunni moa pelikaani pitohui pulu ruokki siira strutsi suula tavi tukaani undulaatti \
  akaatti akvamariini ametisti baryytti berylli fluoriitti granaatti hypersteeni jade jaspis karneoli korundi kuukivi malakiitti meripihka \
  opaali peridootti rubiini safiiri sitriini smaragdi spektroliitti spinelli timantti topaasi turkoosi turmaliini vuorikide zirkoni \
  | sort -n
