#!/bin/bash

set -e

export LC_ALL=C
parallel -i -j100 timeout 3 ssh -oBatchMode=yes -oConnectTimeout=2 {} ppc-helpers/get-my-load "$@" -- \
  albatrossi broileri dodo drontti emu fasaani flamingo iibis kakadu \
  kalkkuna karakara kasuaari kiuru kiwi kolibri kondori kookaburra \
  koskelo kuikka lunni moa pelikaani piekana pulu ruokki sorsa strutsi \
  suula tavi tukaani undulaatti akaatti akvamariini ametisti baryytti \
  berylli dioptaasi fluoriitti granaatti hypersteeni jade jaspis karneoli \
  korundi kuukivi lapislatsuli malakiitti meripihka opaali peridootti \
  rubiini safiiri sitriini smaragdi spektroliitti spinelli timantti \
  topaasi turkoosi turmaliini vuorikide zirkoni \
  | sort
